name: dorm
version: 1.0.42
author: Frank Pepermans <frank@igindo.com>
description: "[Deprecated library] - please use other ORM libraries on pub"
homepage: https://github.com/frankpepermans/dorm
documentation: http://igindo.com/dart/dorm/index.html
dependencies:
  source_gen: '>=0.5.0'
dev_dependencies:
  build_runner: '>=0.1.0'
  test: any
  benchmark_harness: any
dependency_overrides:
  build: ^0.9.0
  source_gen: '>=0.5.0 <0.6.0'