name: dorm
version: 0.3.8
author: Frank Pepermans <frank@igindo.com>
description: "Dorm is an ORM mapping on the client, the goal is to hook it up with\
  \ existing server-side ORM solutions (Hibernate, EntityFramework, ...)\r\n\r\nThe\
  \ example includes a JSON based Dart server for testing purposes.\r\n\r\nYou can\
  \ also generate client-side entities using build_entities.dart, any changes to the\
  \ bin/dbo JSON files will be reflected."
homepage: https://github.com/frankpepermans/dorm
documentation: http://igindo.com/dart/dorm/index.html
dependencies:
  observe: any
dev_dependencies:
  browser: any
  dart_flex: 0.4.9
  unittest: any
